[package]
name = "haiyu-sabi-core"
version.workspace = true
authors.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
